FROM node:slim
WORKDIR /app
COPY package.json .
RUN npm install
COPY . ./
COPY ./src/devData ./dist/devData
COPY ./src/config.env ./dist/config.env
RUN npx tsc
ENV PORT=3002
EXPOSE ${PORT}
CMD [ "npm","run","start" ]