FROM node:latest
WORKDIR /app
COPY package.json .
RUN if [ "$NODE_ENV" = "development" ]; then \
      npm install; \
    else \
      npm install --only=production; \
    fi
# RUN if [ "$NODE_ENV" = "development" ]; then \
#       npm install; \
#     else \
#       npm install --only=production; \
#     fi
COPY . ./


EXPOSE 3000
CMD if["$NODE_ENV"="developnment"]; then \
        ["npm","run","start"]; \
      else \
        ["npm","run","dev"]; \
      fi