FROM node:20.9.0-alpine
WORKDIR /app
COPY package.json .
RUN if [ "$NODE_ENV" = "development" ]; then \
      npm install; \
    else \
      npm install --only=production; \
    fi

COPY . ./
EXPOSE 3000
RUN npm run build
CMD [ "npm","run", "dev" ]